### ISSUE TITLE
fingerprints.pk

### ISSUE THREAD

**Issue by onelysun** [elcorto/imagecluster#1]
Sorry，where is fingerprints.pk？

**Comment by elcorto** [comment]
Hi, thanks for your interest. Have a look at the example in the README file:

```python
>>> main.main('/path/to/testpics/', sim=0.5)
no fingerprints database /path/to/testpics/fingerprints.pk found
```

So it is `/path/to/testpics/fingerprints.pk`.

**Comment by onelysun** [comment]
Thank for your reply, and now I have another issue. How to set the number of cluster in this code?

**Comment by elcorto** [comment]
You do not define the number of clusters beforehand. Instead you choose a value for the similarity index `sim=0...1` and thereby define where to cut the dendogram build up by the hierarchical clustering. That gives you the clusters at that level of similarity (`sim=0` -> `ncluster=1 cluster_size=nimages`, `sim=1` -> `ncluster=nimages cluster_size=1`). Note that we don't report single-file clusters, though (`imagecluster.make_links()`), so with `sim` close to 1, you may not get any clusters at all, unless you have very similar images.

Thanks for the question, I'll update the docs to make that more clear.

**Comment by onelysun** [comment]
Thank you very much! I got it!
