### ISSUE TITLE
Generate the dedrogram

### ISSUE THREAD

**Issue by SionHu** [elcorto/imagecluster#13]
Great work and very instructive documentation! However, I didn't see any instruction on generating the dendrogram showing on the "Method" page. Could you tell me how you guys generate the dendrogram using your hierarchical clustering method? 

Thanks ahead!

**Comment by elcorto** [comment]
Hi, thanks for your interest. Check out [examples/plot_dendrogram.py](https://github.com/elcorto/imagecluster/blob/master/examples/plot_dendrogram.py) :)

This script assumes that your images are in a dir called `pics`. Basically, I use `scipy.cluster.hierarchy.dendrogram()` which does the plot (thanks, scipy!).

If you want to reproduce [the 25 image example from the documentation](https://elcorto.github.io/imagecluster/written/usage.html#minimal-example), which is in fact where the dendrogram plot comes from, then this part of the docs shows how to download and select a subset of the INRIA Holiday image dataset using [examples/inria_holiday.sh](https://github.com/elcorto/imagecluster/blob/master/examples/inria_holiday.sh).

Note: I used this so far only with tensorflow 1.x + keras and the requirements file doesn't specify versions (need to update and test myself). Let me know how things go in case you run the script as is. Thanks!


Cheers,
Steve
