### ISSUE TITLE
How to pick one most representative images from each clusters?

### ISSUE THREAD

**Issue by CharlieZhaoyl** [elcorto/imagecluster#15]
Hi, thanks for your work!  I have successfully run the code and gotten clusters of images. And now I hope to pick the most representative images from each cluster. Could you plz give me some advice how how to do it?

**Comment by elcorto** [comment]
Note: With the current implementation of clustering, the method described above only works when you don't use time distance scaling, since we apply this on-the-fly in `calc.cluster`, while `fingerprints` are unchanged.

**Comment by elcorto** [comment]
Close, inactive OP.

**Comment by CharlieZhaoyl** [comment]
Thanks for your response! I notice that in some paper, they will do cluster in a small dataset, and store the center of each clusters in future usage. Does this method make sense in our implementation? Thanks！

**Comment by elcorto** [comment]
"Some paper" is not that helpful, but nevertheless this sounds like the method I describe above, if I understood you correctly. I have no time to implement something like this ATM, in case you do, I'd be glad to test it. And as mentioned, it probably won't work with time distance scaling.

**Comment by CharlieZhaoyl** [comment]
Understand, thanks for your help！

**Comment by elcorto** [comment]
As mentioned, I haven't done much research on how to do that so far, there are probably tons of methods for this. The one I outlined is the first that came to mind. If you have interesting resources (such as the paper you mentioned), feel free to drop them here.
