### ISSUE TITLE
ImportError: cannot import name 'main'

### ISSUE THREAD

**Issue by zaman-mughal** [elcorto/imagecluster#4]
I am unable to run the example. stuck in first import line. Code is running as it has no module name main. None of the other help in form of docstring is available. Kindly rectify the issue at your earliest.

**Issue:** 

```
 ImportError                               Traceback (most recent call last)
<ipython-input-2-3a7d49ef9779> in <module>()
----> 1 from imagecluster import main

ImportError: cannot import name 'main'
```

**Comment by elcorto** [comment]
This looks like an installation issue. How did you install the package? If with `pip`, what does `pip show imagecluster` say? Note that we use Python 3, so your system might have a separate `pip3` command (Debian-ish systems, I guess). You can also just set `PYTHONPATH=$PYTHONPATH:/path/to/imagecluster`, given that you have all dependencies listed in `setup.py` already installed. Can you import `imagecluster`? If so, what's the output of `imagecluster?` in `ipython`?

**Comment by elcorto** [comment]
Closing due to inactive OP.
