### ISSUE TITLE
No module named 'PIL'

### ISSUE THREAD

**Issue by Eilva** [elcorto/imagecluster#7]
>>> from imagecluster import main
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    from imagecluster import main
  File "c:\users\eva\desktop\imageclustering\imagecluster-master\imagecluster\main.py", line 3, in <module>
    from imagecluster import calc as ic
  File "c:\users\eva\desktop\imageclustering\imagecluster-master\imagecluster\calc.py", line 7, in <module>
    import PIL.Image
ModuleNotFoundError: No module named 'PIL'

**Comment by Eilva** [comment]
Hi. I run the first line code('from imagecluster import main') and this error pop out. Do you mind to solve this ?  and share how the script runs? also just to check the image directory is under 'pics/'?

**Comment by elcorto** [comment]
Seems like you don't have PIL (Python Imaging Library) installed (I use [Pillow](https://pillow.readthedocs.io/en/stable/)). Installing with pip will pull all dependencies (see [requirements.txt](https://github.com/elcorto/imagecluster/blob/master/requirements.txt)). Use `pip install -r requirements.txt [other options]` if pip (or pip3 depending on your system) doesn't pick up the file automatically. Also, make sure to run the tests. See sections "Install" and "Tests" in the README.

**Comment by Eilva** [comment]
Thanks. It works after pip install pillow. I tried to run the pytest tests.py. got issues on "111: PermissionError". Do you know how to solve it?
![testerror](https://user-images.githubusercontent.com/40584572/54174038-66769300-44bf-11e9-9ff4-0e4be80ad901.JPG)

**Comment by elcorto** [comment]
I'm afraid I cannot debug this since I don't use Windows.

However, if the test arrives at this point and there haven't been other exceptions before, then it passed. To check, you can replace the last two lines in the `finally` block by just `pass` (and remove the temp file manually later). If the test passes then you are good to go.

**Comment by Eilva** [comment]
okayokay. Thanks!

**Comment by Eilva** [comment]
okayokay. Thanks!
